version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mantra0217
      MYSQL_DATABASE: seosadb
    volumes:
      - ./mysql_config:/etc/mysql/conf.d:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "-pmantra0217", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  seosa:
    build:
      context: .
    container_name: seosa
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
